# Generated by Django 4.0.4 on 2022-04-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_produc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Product',
        ),
    ]
